<?php

namespace Blog\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BiographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiographyRepository extends EntityRepository
{
}
