<?php

namespace Blog\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function getComments($idPost){
        $comments =$this->getDoctrine()->getManager()
                    ->getRepository('BlogFrontBundle:Comment')
                    ->findBy(array('posts'=>$idPost));
        return $comments;
    }
}
