<?php

namespace Blog\FrontBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsers(){
        $users = $this->getEntityManager()
            ->createQuery('SELECT user FROM BlogFrontBundle:User user ORDER BY user.name ASC');
        return $users->getResult();
    }
}
