route_index:
    path:     /
    defaults: { _controller: BlogFrontBundle:Default:index }

route_view:
    path:   /post/{id}
    defaults: { _controller: BlogFrontBundle:Post:view }

route_about:
    path:   /about
    defaults: { _controller: BlogFrontBundle:Default:about }

route_show:
    path:   /lastpost/{nbPosts}
    defaults: { _controller: BlogFrontBundle:Post:showLastPost }

route_user:
    path:     /users
    defaults: { _controller: BlogFrontBundle:User:list }
